[project]
name = "graphql-authz-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "graphql-core>=3.2.6",
    "jsonpath-ng>=1.7.0",
    "pydantic>=2.11.9",
    "pyyaml>=6.0.2",
    "requests>=2.32.5",
    "typer>=0.17.4",
]
[dependency-groups]
dev = [
    "pytest>=8.4.2",
]

[project.scripts]
gqlproxy = "graphql_authz_proxy.cli:typer_app"
